### ISSUE TITLE
Underline squigglies are red

### ISSUE THREAD

**Issue by supermitch** [UstymUkhman/matrix-theme#1]
Underlines are still in red, I believe they should be green:

<img width="171" alt="image" src="https://github.com/UstymUkhman/matrix-theme/assets/1152280/1c1c77e3-d35d-4ebb-9bfb-35d78d74de2b">

**Comment by UstymUkhman** [comment]
Hi @supermitch! Thanks for your feedback, I will try to fix this if possible as soon as I find some time to come back to this project. In the meantime, feel free to star this theme if you like it to keep me motivated work in it futher.

**Comment by UstymUkhman** [comment]
I've changed my mind here: there is already a red color used in this theme in case of errors, it is `#d40000`. These are errors and the goal is to attract user's attention as much as possible to any kind of error in order to fix it asap. Since everything else is black or green, this red color should be immediately visible.
